config/routes.rb
Rails.application.routes.draw do
  resources :packagings
  root to: "packagings#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/packaging.rb
class Packaging < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/packagings_controller.rb
class PackagingsController < ApplicationController
  before_action :set_packaging, only: [:show, :edit, :update, :destroy]

  # GET /packagings
  # GET /packagings.json
  def index
    @packagings = Packaging.all
  end

  # GET /packagings/1
  # GET /packagings/1.json
  def show
  end

  # GET /packagings/new
  def new
    @packaging = Packaging.new
    @packagings = Packaging.all
  end

  # GET /packagings/1/edit
  def edit
  end

  # POST /packagings
  # POST /packagings.json
  def create
    @packaging = Packaging.new(packaging_params)

    respond_to do |format|
      if @packaging.save
        format.html { redirect_to @packaging, notice: 'Packaging was successfully created.' }
        format.json { render :show, status: :created, location: @packaging }
      else
        format.html { render :new }
        format.json { render json: @packaging.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /packagings/1
  # PATCH/PUT /packagings/1.json
  def update
    respond_to do |format|
      if @packaging.update(packaging_params)
        format.html { redirect_to @packaging, notice: 'Packaging was successfully updated.' }
        format.json { render :show, status: :ok, location: @packaging }
      else
        format.html { render :edit }
        format.json { render json: @packaging.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packagings/1
  # DELETE /packagings/1.json
  def destroy
    @packaging.destroy
    respond_to do |format|
      format.html { redirect_to packagings_url, notice: 'Packaging was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_packaging
      @packaging = Packaging.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def packaging_params
      params.require(:packaging).permit(:date, :name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/packagings_helper.rb
module PackagingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Packagingmuseum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid"></div>

      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" href="/packagings/">Packagings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/packagings/new/">Edit</a>
        </li>
      </ul>

      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/packagings/_form.html.erb
<%= form_with(model: packaging, local: true) do |form| %>
  <% if packaging.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(packaging.errors.count, "error") %> prohibited this packaging from being saved:</h2>

      <ul>
      <% packaging.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/packagings/edit.html.erb
<h1>Editing Packaging</h1>

<%= render 'form', packaging: @packaging %>

<%= link_to 'Show', @packaging %> |
<%= link_to 'Back', packagings_path %>

app/views/packagings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Packagings</h1>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% @packagings.each_with_index do |packaging, index| %>
      <div class="carousel-item <%= 'active' if index.zero? %>">
        <img class="d-block w-100" src="<%= packaging.image %>" alt="First slide">
          <div class="carousel-caption d-none d-md-block">
            <h5><%= packaging.date %></h5>
            <p><%= packaging.name %></p>
          </div>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/packagings/new.html.erb
<h1>New Packaging</h1>

<%= render 'form', packaging: @packaging %>


<h1>Edit</h1>

<table>
  <tbody>
    <% @packagings.each do |packaging| %>
      <tr>
        <td><%= packaging.date %></td>
        <td><%= packaging.name %></td>
        <td><%= packaging.image %></td>
        <td><%= link_to 'Show', packaging %></td>
        <td><%= link_to 'Edit', edit_packaging_path(packaging) %></td>
        <td><%= link_to 'Destroy', packaging, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', packagings_path %>

app/views/packagings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @packaging.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @packaging.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @packaging.image %>
</p>

<%= link_to 'Edit', edit_packaging_path(@packaging) %> |
<%= link_to 'Back', packagings_path %>